=== code-of-kpp/KOIB/Croc.Bpc/Printing/Data/Schemas/ReportTemplate.xsd
<?xml version="1.0" encoding="utf-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://localhost/Schemas/SIB2003/ReportTemplate"
targetNamespace="http://localhost/Schemas/SIB2003/ReportTemplate" elementFormDefault="qualified"> 
    <xs:element name="ReportTemplate"> 


        <xs:complexType> 
            <xs:sequence> 
                <xs:element name="Parameters" minOccurs="0"> 


                    <xs:complexType> 
                        <xs:sequence> 
                            <xs:element name="Parameter" type="xs:string" maxOccurs="unbounded"> 


                            </xs:element> 
                        </xs:sequence> 
                    </xs:complexType> 
                </xs:element> 
                <xs:element name="Header" type="PlainContent" minOccurs="0"> 


                </xs:element> 
                <xs:element name="PageHeader" type="PlainContent" minOccurs="0"> 


                </xs:element> 
                <xs:element name="Table" minOccurs="0"> 


                    <xs:complexType> 
                        <xs:complexContent> 
                            <xs:extension base="TableContent"> 
                                <xs:attribute name="dotted" type="xs:boolean"> 


                                </xs:attribute> 
                            </xs:extension> 
                        </xs:complexContent> 
                    </xs:complexType> 
                </xs:element> 
                <xs:element name="PageFooter" type="PlainContent" minOccurs="0"> 


                </xs:element> 
                <xs:element name="Footer" type="PlainContent" minOccurs="0"> 


                </xs:element> 
            </xs:sequence> 
            <xs:attribute name="name" type="xs:string" use="required"> 


            </xs:attribute> 
            <xs:attribute name="restriction" type="xs:string"> 


            </xs:attribute> 
            <xs:attribute name="claspFooter" type="xs:boolean" default="true"> 


            </xs:attribute> 
            <xs:attribute name="pageNumbered" type="xs:boolean" default="true"> 


            </xs:attribute> 
      <xs:attribute name="font" type="xs:string"> 


      </xs:attribute> 
      <xs:attribute name="font-size" type="xs:int" default="9"> 


      </xs:attribute> 
      <xs:attribute name="margin-left" type="xs:int" default="-1"> 


      </xs:attribute> 
      <xs:attribute name="margin-right" type="xs:int" default="-1"> 


      </xs:attribute> 
      <xs:attribute name="margin-top" type="xs:int" default="-1"> 


      </xs:attribute> 
      <xs:attribute name="margin-bottom" type="xs:int" default="-1"> 


      </xs:attribute> 
    </xs:complexType> 
    </xs:element> 
    <xs:complexType name="IfClause"> 
        <xs:attribute name="condition" type="xs:string" use="required"> 


        </xs:attribute> 
        <xs:attribute name="not" type="xs:boolean"> 


        </xs:attribute> 
    </xs:complexType> 
    <xs:complexType name="PlainIfClause"> 
        <xs:complexContent> 
            <xs:extension base="IfClause"> 
                <xs:sequence> 
                    <xs:element name="Then" type="PlainContent" minOccurs="0"> 


                    </xs:element> 
                    <xs:element name="Else" type="PlainContent" minOccurs="0"> 


                    </xs:element> 
                </xs:sequence> 
            </xs:extension> 
        </xs:complexContent> 
    </xs:complexType> 
    <xs:complexType name="TableIfClause"> 
        <xs:complexContent> 
            <xs:extension base="IfClause"> 
                <xs:sequence> 
                    <xs:element name="Then" type="TableBody" minOccurs="0"> 


                    </xs:element> 
                    <xs:element name="Else" type="TableBody" minOccurs="0"> 


                    </xs:element> 
                </xs:sequence> 
            </xs:extension> 
        </xs:complexContent> 
    </xs:complexType> 
    <xs:complexType name="PlainContent"> 
        <xs:sequence minOccurs="0" maxOccurs="unbounded"> 
            <xs:choice> 
                <xs:element name="Line" minOccurs="0" maxOccurs="unbounded"> 


                    <xs:complexType mixed="true"> 
                        <xs:complexContent mixed="true"> 
                            <xs:extension base="PlainLine"/> 
                        </xs:complexContent> 
                    </xs:complexType> 
                </xs:element> 
                <xs:element name="If" type="PlainIfClause" minOccurs="0" maxOccurs="unbounded"> 


                </xs:element> 
                <xs:element name="For" type="PlainForClause" minOccurs="0" maxOccurs="unbounded"> 


                </xs:element> 
                <xs:element name="SetCurrentRow" minOccurs="0"> 


                </xs:element> 
            </xs:choice> 
        </xs:sequence> 
    </xs:complexType> 
    <xs:complexType name="TableBody"> 
        <xs:sequence minOccurs="0" maxOccurs="unbounded"> 
            <xs:choice> 
                <xs:element name="Line" minOccurs="0" maxOccurs="unbounded"> 


                    <xs:complexType> 
                        <xs:complexContent> 
                            <xs:extension base="TableLine"> 
                                <xs:attributeGroup ref="IfCondition"/> 
                            </xs:extension> 
                        </xs:complexContent> 
                    </xs:complexType> 
                </xs:element> 
                <xs:element name="If" type="TableIfClause" minOccurs="0" maxOccurs="unbounded"> 


                </xs:element> 
                <xs:element name="For" type="TableForClause" minOccurs="0" maxOccurs="unbounded"> 


                </xs:element> 
                <xs:element name="SetCurrentRow" minOccurs="0"> 


                </xs:element> 
            </xs:choice> 
        </xs:sequence> 
    </xs:complexType> 
    <xs:complexType name="PlainForClause"> 
        <xs:sequence> 
            <xs:element name="Body" type="PlainContent"> 


            </xs:element> 
        </xs:sequence> 
        <xs:attributeGroup ref="ForCondition"/> 
    </xs:complexType> 
    <xs:complexType name="LinePart" mixed="true"> 
        <xs:sequence> 
            <xs:element name="Parts" minOccurs="0"> 


                <xs:complexType> 
                    <xs:sequence> 
                        <xs:element name="Part" type="LinePart" minOccurs="0" maxOccurs="unbounded"> 


                        </xs:element> 
                    </xs:sequence> 
                </xs:complexType> 
            </xs:element> 
        </xs:sequence> 
        <xs:attributeGroup ref="IfCondition"/> 
    </xs:complexType> 
    <xs:complexType name="TableForClause"> 
        <xs:sequence> 
            <xs:element name="Body" type="TableBody"> 


            </xs:element> 
        </xs:sequence> 
        <xs:attributeGroup ref="ForCondition"/> 
    </xs:complexType> 
    <xs:attributeGroup name="ForCondition"> 
        <xs:attribute name="each" type="xs:string" use="required"> 


        </xs:attribute> 
        <xs:attribute name="in" type="xs:string" use="required"> 


        </xs:attribute> 
    </xs:attributeGroup> 
    <xs:attributeGroup name="IfCondition"> 
        <xs:attribute name="condition" type="xs:string"> 


        </xs:attribute> 
        <xs:attribute name="not" type="xs:boolean"> 


        </xs:attribute> 
    </xs:attributeGroup> 
    <xs:complexType name="TableContent"> 
        <xs:sequence> 
            <xs:element name="Header"> 


                <xs:complexType> 
                    <xs:sequence> 
                        <xs:element name="Col" maxOccurs="unbounded"> 


                            <xs:complexType mixed="true"> 
                                <xs:attributeGroup ref="FontDefinition"/> 
                                <xs:attribute name="width" type="xs:int"> 


                                </xs:attribute> 
                                <xs:attribute name="count" type="xs:string"> 


                                </xs:attribute> 
                            </xs:complexType> 
                        </xs:element> 
                    </xs:sequence> 
                </xs:complexType> 
            </xs:element> 
            <xs:element name="Body" type="TableBody"> 


            </xs:element> 
        </xs:sequence> 
    </xs:complexType> 
    <xs:attributeGroup name="FontDefinition"> 
        <xs:attribute name="fontSize" type="xs:string"> 


        </xs:attribute> 
        <xs:attribute name="bold" type="xs:boolean"> 


        </xs:attribute> 
        <xs:attribute name="italic" type="xs:boolean"> 


        </xs:attribute> 
        <xs:attribute name="align" type="Croc.SibApp.Printing.LineAlign"> 


        </xs:attribute> 
    </xs:attributeGroup> 
    <xs:complexType name="PlainLine" mixed="true"> 
        <xs:complexContent mixed="true"> 
            <xs:extension base="LinePart"> 
                <xs:attributeGroup ref="FontDefinition"/> 
                <xs:attribute name="split" type="xs:string"> 


                </xs:attribute> 
                <xs:attribute name="trim" type="xs:boolean"> 


                </xs:attribute> 
            </xs:extension> 
        </xs:complexContent> 
    </xs:complexType> 
    <xs:complexType name="TableLine"> 
        <xs:sequence> 
            <xs:element name="Cols"> 


                <xs:complexType> 
                    <xs:sequence> 
                        <xs:element name="Col" maxOccurs="unbounded"> 


                            <xs:complexType mixed="true"> 
                                <xs:complexContent mixed="true"> 
                                    <xs:extension base="LinePart"> 
                                        <xs:attribute name="each" type="xs:string"> 


                                        </xs:attribute> 
                                        <xs:attribute name="in" type="xs:string"> 


                                        </xs:attribute> 
                                    </xs:extension> 
                                </xs:complexContent> 
                            </xs:complexType> 
                        </xs:element> 
                    </xs:sequence> 
                </xs:complexType> 
            </xs:element> 
        </xs:sequence> 
        <xs:attributeGroup ref="ColDefinition"/> 
        <xs:attribute name="newPage" type="xs:boolean" default="false"> 


        </xs:attribute> 
        <xs:attribute name="resetPageNumber" type="xs:boolean" default="false"> 


        </xs:attribute> 
    </xs:complexType> 
    <xs:attributeGroup name="ColDefinition"> 
        <xs:attributeGroup ref="FontDefinition"/> 
        <xs:attribute name="dotted" type="xs:boolean"> 


        </xs:attribute> 
    </xs:attributeGroup> 
    <xs:simpleType name="Croc.SibApp.Printing.LineAlign"> 


        <xs:restriction base="xs:string"> 
            <xs:enumeration value="Left"> 


            </xs:enumeration> 
            <xs:enumeration value="Right"> 


            </xs:enumeration> 
            <xs:enumeration value="Center"> 


            </xs:enumeration> 
        </xs:restriction> 
    </xs:simpleType> 
</xs:schema>

=== code-of-kpp/KOIB/Croc.Bpc/Printing/Data/Templates/ElectionProtocol.xml
<?xml version="1.0" encoding="utf-8"?> 
<ReportTemplate claspFooter="true" name="ElectionProtocol" font="Verdana" font-size="8" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://localhost/Schemas/SIB2003/ReportTemplate"
si:schemaLocation="http://localhost/Schemas/SIB2003/ReportTemplate ReportTemplate.xsd"> 
  <Parameters> 


    <Parameter>Election</Parameter> 


    <Parameter>withResults</Parameter> 
  </Parameters> 
  <Header> 
    <Line align="Left">Экземпляр № ___</Line> 
    <Line align="Center">{$@Election.Name}</Line> 
    <Line align="Center">{$ElectionManager.SourceData.ElectionDate|d MMMM yyyy года}</Line> 
    <Line align="Center" bold="true">ПРОТОКОЛ</Line> 
    <Line align="Center" split="\n" trim="true">{$@Election.Protocol.Name}</Line> 
    <Line align="Center">Избирательный участок N{$ElectionManager.SourceData.Uik}</Line> 
  </Header> 
  <Body> 
    <Table> 
      <Header> 


        <Col width="3"/> 


        <Col width="65"/> 


        <Col width="4"/> 


        <Col width="28"/> 
      </Header> 
      <Body> 


        <For in="@Election.Protocol.Lines" each="Line"> 
          <Body> 
            <Line> 
              <Cols> 
                <Col>{$@Line.Num}{$@Line.AdditionalNum}</Col> 
                <Col>{$@Line.Name}</Col> 
                <Col> 
                  <Parts> 
                    <Part condition="@withResults">{$@Line.Value}</Part> 
                    <Part not="true" condition="@withResults">0</Part> 
                  </Parts> 
                </Col> 
                <Col> 
                  <Parts> 
                    <Part condition="@withResults">({$@Line.Value|#w})</Part> 
                    <Part not="true" condition="@withResults">(ноль)</Part> 
                  </Parts> 
                </Col> 
              </Cols> 
            </Line> 
          </Body> 
        </For> 


        <SetCurrentRow>{$@Election.Protocol.LatestLineNumber}</SetCurrentRow> 


        <For in="@Election.Candidates" each="Candidate"> 
          <Body> 
            <If not="true" condition="@Candidate.Disabled"> 
              <Then> 


                <Line> 
                  <Cols> 
                    <Col>{$CurrentRow}</Col> 
                    <Col> 
                      <Parts> 
                        <Part condition="@Candidate.LastName">{$@Candidate.LastName|#u}</Part> 
                        <Part condition="@Candidate.FirstName"> {$@Candidate.FirstName}</Part> 
                        <Part condition="@Candidate.Patronymic"> {$@Candidate.Patronymic}</Part> 
                      </Parts> 
                    </Col> 
                    <Col> 
                      <Parts> 
                        <Part
ondition="@withResults">{$VotingResultManager.VotingResults.VotesCount&lt;$VoteKey.ctor&lt;;;;$@Candidate.Id;$@Election.ElectionId;&gt;&gt;}</Part> 
                        <Part not="true" condition="@withResults">0</Part> 
                      </Parts> 
                    </Col> 
                    <Col> 
                      <Parts> 
                        <Part
ondition="@withResults">({$VotingResultManager.VotingResults.VotesCount&lt;$VoteKey.ctor&lt;;;;$@Candidate.Id;$@Election.ElectionId;&gt;&gt;|#w})</Part> 
                        <Part not="true" condition="@withResults">(ноль)</Part> 
                      </Parts> 
                    </Col> 
                  </Cols> 
                </Line> 
              </Then> 
              <Else> 


                <If condition="@Election.Protocol.DisabledString"> 
                  <Then> 


                    <Line> 
                      <Cols> 
                        <Col>{$CurrentRow}</Col> 
                        <Col> 
                          <Parts> 
                            <Part condition="@Candidate.LastName">{$@Candidate.LastName|#u}</Part> 
                            <Part condition="@Candidate.FirstName"> {$@Candidate.FirstName}</Part> 
                            <Part condition="@Candidate.Patronymic"> {$@Candidate.Patronymic}</Part> 
                          </Parts> 
                        </Col> 
                        <Col>{$@Election.Protocol.DisabledString}</Col> 
                        <Col/> 
                      </Cols> 
                    </Line> 
                  </Then> 
                </If> 
              </Else> 
            </If> 
          </Body> 
        </For> 
      </Body> 
    </Table> 
  </Body> 
  <PageFooter> 
    <Line align="Left"/> 
    <Line align="Left">Председатель участковой избирательной комиссии</Line> 
    <If not="true" condition="ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Chairman&gt;"> 
      <Then> 
        <Line align="Right">______________________    _________________________________________</Line> 
      </Then> 
      <Else> 
        <Line align="Right">{$ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Chairman&gt;}    _________________________________________</Line> 
      </Else> 
    </If> 
    <Line align="Right">(фамилия, инициалы)                          (подпись либо причина отсутствия,    </Line> 
    <Line align="Right">                                     отметка об особом мнении)         </Line> 
    <Line align="Left">Заместитель председателя комиссии</Line> 
    <If not="true" condition="ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;ChairmanAssistant&gt;"> 
      <Then> 
        <Line align="Right">______________________    _________________________________________</Line> 
      </Then> 
      <Else> 
        <Line align="Right">{$ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;ChairmanAssistant&gt;}
________________________________________</Line> 
      </Else> 
    </If> 
    <Line align="Left">Секретарь комиссии</Line> 
    <If not="true" condition="ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Secretary&gt;"> 
      <Then> 
        <Line align="Right">______________________    _________________________________________</Line> 
      </Then> 
      <Else> 
        <Line align="Right">{$ElectionManager.SourceData.GetCommitteeMemberInitialByType&lt;Secretary&gt;}    _________________________________________</Line> 
      </Else> 
    </If> 
    <Line align="Left">Члены комиссии:</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line align="Right">______________________    _________________________________________</Line> 
    <Line/> 
    <Line align="Left" bold="true">    МП       Протокол подписан "___" _____ {$CurrentDateTime.Year} года   в ___ часов ___ минут</Line> 
  </PageFooter> 
  <Footer> 
    <Line>Сведения о количестве поступивших в участковую избирательную комиссию</Line> 
    <Line>в день голосования и до окончания подсчета голосов избирателей жалоб (заявлений),  __________ _________________________</Line> 
    <Line>прилагаемых к протоколу                                                                                                цифрами          прописью</Line> 
  </Footer> 
</ReportTemplate>
